"""Publish a staged job to the Hugging Face Hub. Default visibility is private."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Protocol

from datasets import load_from_disk
from huggingface_hub import DatasetCard, HfApi, whoami

from embedforge import __version__
from embedforge.errors import EmbedForgeError
from embedforge.hfdata import hf_token
from embedforge.plan import default_output_repo
from embedforge.shapes import Job, JobStatus, PublishResult, replace_job
from embedforge.store import JobStore


class Publisher(Protocol):
    def publish(
        self,
        *,
        repo_id: str,
        private: bool,
        revision: str | None,
        dataset_dir: Path,
        card: str,
        provenance_yaml: str,
        token: str | None,
    ) -> str: ...


@dataclass
class HuggingFacePublisher:
    def publish(
        self,
        *,
        repo_id: str,
        private: bool,
        revision: str | None,
        dataset_dir: Path,
        card: str,
        provenance_yaml: str,
        token: str | None,
    ) -> str:
        if not token:
            raise EmbedForgeError(
                "API credentials must be supplied through environment variables.\n"
                "Set HF_TOKEN in your shell environment."
            )
        dataset = load_from_disk(str(dataset_dir))
        dataset.push_to_hub(
            repo_id,
            private=private,
            token=token,
            revision=revision,
        )
        DatasetCard(card).push_to_hub(repo_id, token=token)
        api = HfApi(token=token)
        api.upload_file(
            path_or_fileobj=provenance_yaml.encode("utf-8"),
            path_in_repo="embedforge.yaml",
            repo_id=repo_id,
            repo_type="dataset",
            token=token,
        )
        return f"https://huggingface.co/datasets/{repo_id}"


def resolve_namespace(explicit: str | None) -> str | None:
    if explicit:
        return explicit
    token = hf_token()
    if not token:
        return None
    try:
        identity = whoami(token=token)
    except Exception:
        return None
    if isinstance(identity, dict):
        name = identity.get("name")
        return name if isinstance(name, str) else None
    name = getattr(identity, "name", None)
    return name if isinstance(name, str) else None


def build_dataset_card(job: Job, provenance_yaml: str) -> str:
    source = job.source
    embedding = job.embedding
    source_url = f"https://huggingface.co/datasets/{source.repository}"
    license_line = source.license or "unknown"
    return (
        f"---\n"
        f"license: {license_line}\n"
        f"---\n\n"
        f"# {job.output.repo.split('/')[-1]}\n\n"
        f"Derived embedding dataset generated by "
        f"[EmbedForge](https://github.com/klgraham/embedforge) "
        f"{__version__}.\n\n"
        f"## Source\n\n"
        f"- Dataset: [{source.repository}]({source_url})\n"
        f"- Revision: `{source.revision}`\n"
        f"- Config: `{source.config or 'default'}`\n"
        f"- Split: `{source.split or 'unknown'}`\n"
        f"- License: `{license_line}` (inherited from the source dataset)\n\n"
        f"## Embedding\n\n"
        f"- Provider: `{embedding.provider}`\n"
        f"- Model: `{embedding.model}`\n"
        f"- Dimensions: `{embedding.dimensions}`\n"
        f"- Source column(s): {', '.join(f'`{name}`' for name in embedding.source_columns)}\n"
        f"- Output column: `{embedding.column}`\n\n"
        f"## Provenance\n\n"
        f"```yaml\n{provenance_yaml.rstrip()}\n```\n\n"
        f"## License\n\n"
        f"This dataset retains the license, attribution requirements, and usage "
        f"restrictions of its source dataset, along with any applicable terms "
        f"associated with the embedding model or service used to generate the "
        f"embeddings.\n"
    )


def publish_job(
    job_id: str,
    *,
    repo: str | None = None,
    private: bool = True,
    revision: str | None = None,
    store: JobStore | None = None,
    publisher: Publisher | None = None,
    namespace: str | None = None,
) -> PublishResult:
    job_store = store or JobStore()
    job = job_store.load(job_id)
    output = job_store.output_dir(job_id)
    if not output.exists():
        raise EmbedForgeError(f"job {job_id} has no staged output; run it first")
    if job.status is JobStatus.CREATED:
        raise EmbedForgeError(f"job {job_id} has not finished running")
    provenance = job_store.load_provenance(job_id)
    card = build_dataset_card(job, provenance.to_yaml())
    job_store.write_card(job_id, card)
    repo_id = repo or job.output.repo
    if "/" not in repo_id:
        resolved_ns = resolve_namespace(namespace)
        if resolved_ns:
            repo_id = f"{resolved_ns}/{repo_id}"
        else:
            repo_id = default_output_repo(
                job.source.repository,
                job.embedding.provider,
                job.embedding.model,
                namespace=resolved_ns,
            )
            if "/" not in repo_id:
                raise EmbedForgeError("pass --repo owner/name or `embed set hf_namespace NAME`")
    worker = publisher or HuggingFacePublisher()
    url = worker.publish(
        repo_id=repo_id,
        private=private,
        revision=revision,
        dataset_dir=output,
        card=card,
        provenance_yaml=provenance.to_yaml(),
        token=hf_token(),
    )
    job_store.save_job(replace_job(job, status=JobStatus.PUBLISHED, published_repo=repo_id))
    return PublishResult(
        repo_id=repo_id,
        private=private,
        revision=revision,
        url=url,
        card=card,
    )
